-- Create public Storage bucket for campaign images generated by PiApp
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'campaign-images',
  'campaign-images',
  true,
  10485760, -- 10 MB per file
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

-- Public read: anyone can fetch images via the public URL
DROP POLICY IF EXISTS "public_read_campaign_images" ON storage.objects;
CREATE POLICY "public_read_campaign_images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'campaign-images');

-- Server upload: anon key (used by the Express server) can insert/upsert images
DROP POLICY IF EXISTS "anon_insert_campaign_images" ON storage.objects;
CREATE POLICY "anon_insert_campaign_images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'campaign-images');

-- Allow re-generation to overwrite existing frames (upsert = true)
DROP POLICY IF EXISTS "anon_update_campaign_images" ON storage.objects;
CREATE POLICY "anon_update_campaign_images"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'campaign-images')
  WITH CHECK (bucket_id = 'campaign-images');
